build:
  system_packages:
    - libdbus-1-dev
    - python3-dbus
    - libgirepository1.0-dev
    - pkg-config
    - libcairo2-dev
  python_packages:
    - boto3==1.35.83
    - botocore==1.35.83
    - dbus-python==1.2.18
    - launchpadlib==1.10.16
    - wadllib==1.3.6
    - httplib2==0.20.2
    - oauthlib==3.2.0
    - keyring==23.5.0
    - numpy==1.25.0
    - protobuf==5.29.1
    - torch==2.4.0
    - torchvision==0.19.0
    - pillow==10.4.0
    - imageio==2.36.1
    - imageio-ffmpeg==0.5.1
    - tqdm==4.67.1
    - easydict==1.13
    - opencv-python-headless==4.10.0.84
    - scipy==1.14.1
    - rembg==2.0.60
    - onnxruntime==1.20.1
    - trimesh==4.5.3
    - xatlas==0.0.9
    - pyvista==0.44.2
    - pymeshfix==0.17.0
    - igraph==0.11.8
    - git+https://github.com/EasternJournalist/utils3d.git@9a4eb15e4021b67b12c460c7057d642626897ec8
    - xformers==0.0.27.post2
    - spconv-cu120==2.3.6
    - transformers==4.46.3
    - cryptography==3.4.8
    - SecretStorage==3.3.1
    - distro==1.7.0
    - flatbuffers==24.3.25
    - fsspec==2024.10.0
    - importlib-metadata==4.6.4
    - jeepney==0.7.1
    - Jinja2==3.1.4
    - kiwisolver==1.4.7
    - lazr.restfulclient==0.14.4
    - lazr.uri==1.0.6
    - urllib3==2.2.3
    - zipp==1.0.0
    - https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.0.post2/flash_attn-2.7.0.post2+cu12torch2.4cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
    - https://huggingface.co/spaces/JeffreyXiang/TRELLIS/resolve/main/wheels/diff_gaussian_rasterization-0.0.0-cp310-cp310-linux_x86_64.whl?download=true
    - https://huggingface.co/spaces/JeffreyXiang/TRELLIS/resolve/main/wheels/nvdiffrast-0.3.3-cp310-cp310-linux_x86_64.whl?download=true
    - PyGObject==3.42.1
    - PyJWT==2.3.0
    - uv==0.5.9
    - more-itertools==8.10.0
    - charset-normalizer==3.4.0
